name: Newman API Tests
on: 
  workflow_dispatch:
jobs: 
  test: 
    # defaults: 
    #   # run: 
    #   #   working-directory: test
#    environment: staging
    name: "Run tests"
    runs-on: ubuntu-latest
    steps: 
      - name: "Print working directory"
        run: |
         pwd
      - name: "Run tests"
        run: "newman run Req.postman_collection.json"

